[package]
name = "demo"
version = "0.1.0"
authors = ["jiangwu10057"]
edition = "2018"

[profile.dev]
# split-debuginfo = "unpacked"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
